### ISSUE TITLE
Issue with Transparent background

### ISSUE THREAD

**Issue by LouisJS** [wcandillon/react-native-expo-image-cache#42]
In my list of item, i'm having some `PNG` files with transparent background such as : [Image](http://res.cloudinary.com/donglyhya/image/upload/v1520329255/original_file_full_scaled.png)

Here is the [result](http://res.cloudinary.com/donglyhya/image/upload/v1520329357/Screen_Shot_2018-03-06_at_10.42.01_b7pirk.png) when i'm using your Image component (even without preview).

It adds a weird shadow effect.

Thanks for your help.

**Comment by LouisJS** [comment]
Even more obvious with a `resizeMode={"contain"}` => [Here](https://res.cloudinary.com/donglyhya/image/upload/v1520415510/Screen_Shot_2018-03-07_ResizeModeContain.png)

**Comment by wcandillon** [comment]
@LouisJS Thank you for pointing out this bug, I was able to reproduce it. Since images are put on top of each other, transparent images will yield strange results. A quick fix would to set a background color in between layers, would that be a satisfactory solution for you? I'm gonna investigate if there is a more elegant solution available.
